# Generated by Django 5.0.6 on 2024-07-02 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp3', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='media/'),
        ),
    ]
